example_login:
  username: "exampleuser"
  password: "SCRUBBED_PASSWORD"

example_incorrect_login:
  username: "exampleuser 100"
  password: "SCRUBBED_PASSWORD"

open_source_list_of_tables:
  - 2gdpr
  - brandwatch
  - builtwith
  - crunchbaseInvestors
  - glassdoor
  - glassdoorProfile
  - googleJobs
  - greyhatwarfareBuckets
  - greyhatwarfareFiles
  - haveibeenpwned
  - hunterio
  - immuniweb
  - indeedJobs
  - indeedProfile
  - justia
  - openSourceEvidence
  - partnerSearch
  - partnerbase
  - simplywallst
  - thelayoff
  - vtrusotal
  - yahooFinanceInvestors
  - yahooFinanceRevenue
  - yahooFinanceStocks

# Short list for smoke tests. I am using it for 200 response and sure that we have information in the DB
open_source_short_list_of_tables:
  - 2gdpr
  - builtwith
  - glassdoor
  - thelayoff

